// Generated by CoffeeScript 1.7.1

/*
 * admin-site 项目主程序
 * author:YuanXiangDong
 * date: 2015-02-27
 */

(function() {
  var WeixinTools, c, config, debuglog, env, express, fs, p, path, pkg, port, start, _;

  fs = require("fs");

  path = require("path");

  p = require('commander');

  express = require("express");

  _ = require('underscore');

  WeixinTools = require("weixin-tools");

  debuglog = require("debug")("weixin-web::server");

  pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "../package.json")));

  p.version(pkg.version).option('-e, --environment [type]', 'runtime environment of [development, production, testing]', 'development').option('-p, --port [value]', 'runtime port ', '7789').parse(process.argv);


  /*
   * bootstrap config
   */

  env = p.environment || 'development';

  port = p.port || 7789;

  c = require('./config/config');

  config = require('./config/config')[env];

  config.port = port;

  config.version = pkg.version;

  config.root = path.resolve(__dirname, "../");

  start = function(config) {
    return require('./utils/redis_db').init(config, function() {
      var app, options, wxt;
      options = config.weixin || {};
      wxt = new WeixinTools(options.appid, options.secret, options.jsapiList, true);
      require("./utils/weixin_util").init(wxt);

      /*
       * express settings
       */
      app = express();
      require("./config/express")(app, config);

      /*
       * bootstrap routes
       */
      require("./config/routes")(app, wxt, config);

      /*
       * start the app by listening on port
       */
      app.listen(port);
      return console.log("weixin-web web started on port:" + port + ", env:" + env);
    });
  };

  start(config);

}).call(this);
