// Generated by CoffeeScript 1.8.0
(function() {
  var debuglog;

  debuglog = require("debug")("weixin-web:controller:animations");

  exports.home = function(req, res, next) {
    return console.dir(req);
  };

}).call(this);
