// Generated by CoffeeScript 1.7.1
(function() {
  var AUTHORIXZE_URL, debuglog, domainName, redis, weixinUtil, wxt, _loadAccessToken, _loadUserInfo, _sendError;

  debuglog = require("debug")("weixin-web:controller:weixins");

  redis = require('../utils/redis_db').redis;

  weixinUtil = require('../utils/weixin_util');

  AUTHORIXZE_URL = null;

  wxt = null;

  domainName = "";

  _sendError = function(res, err) {
    res.json({
      succuse: false,
      message: err
    });
  };

  _loadAccessToken = function(callback) {
    return wxt.loadAccessToken(function(err, access_token) {});
  };

  _loadUserInfo = function(openid, callback) {
    return redis.hgetall("weixin_userinfo::" + openid, callback);
  };

  exports.init = function(weixinTools, options) {
    console.log("weixins init.");
    AUTHORIXZE_URL = options.authorizeUrl;
    domainName = options.domainName;
    wxt = weixinTools;
  };

  exports.home = function(req, res, next) {
    var authorizeUrl;
    console.log("authorizeUrl:" + AUTHORIXZE_URL);
    authorizeUrl = wxt.generateAuthorizeURL(AUTHORIXZE_URL, "", 'snsapi_base');
    console.log(authorizeUrl);
    return res.redirect(authorizeUrl);
  };

  exports.login = function(req, res, next) {
    var code;
    code = (req.query || {}).code;
    return wxt.loadAuthorzeToken(code, function(err, authorizeToken) {
      var tokenKey;
      if (err != null) {
        return _sendError(res, err);
      }
      if (!((authorizeToken != null) && (authorizeToken.openid != null))) {
        return _sendError(res, new Error('authorizeToken is null'));
      }
      tokenKey = "weixin_au_token::" + authorizeToken.openid;
      if (authorizeToken.scope === 'snsapi_userinfo') {
        wxt.loadUserInfo(authorizeToken.openid, authorizeToken.access_token, "zh-CN", function(err, userinfo) {
          console.dir(userinfo);
          if (err != null) {
            return _sendError(res, err);
          }
          if (!userinfo) {
            return _sendError(res, new Error("not find userinfo"));
          }
          redis.hmset("weixin_userinfo::" + authorizeToken.openid, userinfo, function(err) {
            req.session.userinfo = userinfo;
            res.redirect("/index");
          });
        });
        return;
      }
      return _loadUserInfo(authorizeToken.openid, function(err, userinfo) {
        var authorizeUrl;
        if ((err == null) && (userinfo != null)) {
          req.session.userinfo = userinfo;
          res.redirect("/index");
          return;
        }
        authorizeUrl = wxt.generateAuthorizeURL(AUTHORIXZE_URL, "", 'snsapi_userinfo');
        return res.redirect(authorizeUrl);
      });
    });
  };

  exports.index = function(req, res, next) {
    var url, userinfo;
    userinfo = req.session.userinfo || {};
    console.dir(req);
    url = "http://" + domainName + req.originalUrl;
    weixinUtil.generateConfig(url, function(err, config) {
      if (err != null) {
        return _sendError(res, err);
      }
      console.dir(config);
      res.render("index2", {
        config: config
      });
    });
  };

}).call(this);
