// Generated by CoffeeScript 1.7.1

/*
 * 系统的express配置
 * author: YuanXiangDong
 * date: 2015-02-27
 */

(function() {
  var bodyParser, compress, cookieParser, debuglog, express, methodOverride, morgan, path, session, timeout;

  express = require('express');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  methodOverride = require('method-override');

  timeout = require("connect-timeout");

  morgan = require('morgan');

  session = require('express-session');

  compress = require('compress');

  path = require("path");

  debuglog = require("debug")("weixin-web::config::express");

  module.exports = function(app, config) {
    app.set('showStackError', true);
    app.use(express["static"]("" + config.root + "/public"));
    app.use(timeout(60 * 60 * 1000));
    if (process.env.NODE_ENV !== 'text') {
      app.use(morgan('dev'));
    }
    app.set('views', path.join(config.root, '/views'));
    app.set('view engine', 'jade');
    app.set('view options', {
      pretty: false
    });
    app.use(cookieParser(config.app.cookieSecret));
    app.use(bodyParser({
      limit: '99mb'
    }));
    app.use(methodOverride());
    app.use(session({
      secret: config.app.sessionSecret,
      key: config.app.cookieSecret
    }));
    app.use(function(req, res, next) {
      next();
    });
    app.locals.VERSION = config.version;
    app.locals.APP_NAME = config.app.name;
    return app.locals.TIMESTAMP = Date.now().toString(36);
  };

}).call(this);
