// Generated by CoffeeScript 1.8.0

/*
 * 系统的总路由
 * author:YuanXiangDong
 * date: 2015-02-27
 */

(function() {
  var debuglog;

  debuglog = require("debug")("gama-assets-reup::config::routes");

  module.exports = function(app) {
    var controller;
    controller = require('../controllers/weixins');
    app.route("/").get(controller.home);
    app.use(function(err, req, res, next) {
      if ((err == null) || (err.name === "NotFoundError") || (~err.message.indexOf('not found'))) {
        return next();
      }
      res.status(500).render('500', {
        error: err.stack
      });
    });
    return app.use(function(req, res, next) {
      return res.status(404).render('404', {
        url: req.originalUrl,
        error: 'not found'
      });
    });
  };

}).call(this);
