// Generated by CoffeeScript 1.7.1

/*
 * 系统的总路由
 * author:YuanXiangDong
 * date: 2015-02-27
 */

(function() {
  var debuglog;

  debuglog = require("debug")("gama-assets-reup::config::routes");

  module.exports = function(app, wxt, config) {
    var controller, weixinOptions;
    weixinOptions = config.weixin || {};
    weixinOptions.domainName = config.domainName;
    controller = require('../controllers/weixins');
    controller.init(wxt, weixinOptions);
    app.route("/").get(controller.home);
    app.route("/login").get(controller.login);
    app.route("/index").get(controller.index);
    app.use(function(err, req, res, next) {
      if ((err == null) || (err.name === "NotFoundError") || (~err.message.indexOf('not found'))) {
        return next();
      }
      debuglog("ERROR: " + err);
      res.status(500).render('500', {
        error: err.stack
      });
    });
    return app.use(function(req, res, next) {
      return res.status(404).render('404', {
        url: req.originalUrl,
        error: 'not found'
      });
    });
  };

}).call(this);
