// Generated by CoffeeScript 1.7.1

/*
 * http 相关工具类
 */

(function() {
  var debuglog, xxtea, xxteaKey;

  debuglog = require("debug")("weixin-web:utils:http_utils");

  xxtea = require("xxtea");

  xxteaKey = null;

  exports.generateTimestamp = function() {
    return parseInt(Date.now() / 1000);
  };

  exports.init = function(options) {
    return xxteaKey = options.xxteaKey || '';
  };

  exports.xxteaEncryptObj = function(obj) {
    return xxtea.encrypt(JSON.stringify(obj), xxteaKey);
  };

  exports.xxteaDecryptObj = function(str) {
    var err;
    str = xxtea.decrypt(str, key);
    try {
      return JSON.parse(str);
    } catch (_error) {
      err = _error;
      debuglog("ERROR: " + err);
      return {};
    }
  };

}).call(this);
