// Generated by CoffeeScript 1.7.1
(function() {
  var RANDOM_NAME_KEY, debuglog, _, _redis;

  _ = require("underscore");

  debuglog = require("debug")("weixin-web::utils::redis_db");

  _redis = null;

  RANDOM_NAME_KEY = "auto_random_name";

  module.exports = {
    init: function(env, callback) {
      debuglog("[redis_db::init] start. REDIS_PORT:" + env.REDIS_PORT + " REDIS_HOST:" + env.REDIS_HOST);
      _redis = require("redis").createClient(env.REDIS_PORT, env.REDIS_HOST);
      _redis.select(env.SELECT || 1);
      _redis.debug_mode = env.DEBUG;
      _redis.on("error", function(error) {
        return debuglog("[db.on_error] " + error);
      });
      _redis.on("end", function() {
        return debuglog("[db.on_end]");
      });
      _redis.on("ready", function() {
        debuglog("[db] redis client is ready to server.");
        if (_.isFunction(callback)) {
          return callback();
        }
      });
      _redis.on("reconnecting", function(info) {
        return debuglog("[db] redis client is reconnecting to datastore... delay:" + info.delay + ", attempt:" + info.attempt);
      });
      return this.redis = _redis;
    }
  };

}).call(this);
